Meta:
  Name: my-app
  Protocol: gRPC
  Port: 50050
  UsesClient: true
PubSubs:
- Type: pubsub.redis
  Name: redis-pubsub
  Topic: messages
- Type: pubsub.kafka
  Name: kafka-pubsub
  Topic: messages
Bindings:
- Type: bindings.cron
  Name: cron-binding
- Type: bindings.kafka
  Name: kafka-binding
Services:
- Name: myService
- Name: myOtherService
Components:
- Type: secretstores.local.env
  Name: localenv-secret
- Type: state.redis
  Name: redis-store
- Type: state.postgresql
  Name: postgresql-store
- Type: pubsub.snssqs
  Name: snssqs-pubsub
- Type: bindings.twitter
  Name: twitter-binding